# Packaging Order for Packaging Machine

uint32 order_id
uint32 material_box_id

# An vector containing information to be printed on the material box.
PackageInfo[28] print_info

string prescription_id

# Identifier for who is requesting the service
uint16 requester_id

uint8 target_packaging_machine_id

---

bool success

# This will provide a verbose message
string message
